### ISSUE TITLE
Consider changing representation of `Channel`

### ISSUE THREAD

**Issue by pchiusano** [scalaz/scalaz-stream#23]
From `Process[F, A => F[B]]` to `Process[F, A => Process[F,B]]`. This is more flexible - channel can emit zero or more values for each input, rather than exactly one value. And I suspect can reimplement all the existing combinators. 

Need to do some investigation of this to see if it's possible.

**Comment by djspiewak** [comment]
Can we close this in favor of solely tracking through the broader "new algebra" effort on #383 (and related)?

**Comment by pchiusano** [comment]
Yeah.
