### ISSUE TITLE
upload to maven repository

### ISSUE THREAD

**Issue by advoretsky** [scalaz/scalaz-stream#258]
project builds are absent in maven-central - it fails builds

**Comment by jilen** [comment]
+1 Suprised this excellent library haven't uploaded to maven central repo yet!

**Comment by maslovalex** [comment]
+1 specs2 needs it

**Comment by pchlupacek** [comment]
Folks hence the current sbt version is using bintray as one of the default repos do you think this is still necessary?

**Comment by advoretsky** [comment]
It's only second time I meet mention of [bintray](http://jcenter.bintray.com/). I was stucked trying to build my project with Maven. If adding next snippet solves the problem - Ok.

        <repository>
          <id>central</id>
          <name>bintray</name>
          <url>http://jcenter.bintray.com</url>
        </repository>

Putting it somewhere in Readme.md would help me

**Comment by briantopping** [comment]
That's a temporary fix, but repositories come and go. Capturing a repository like that means that the source may not be able to be built if bintray were to not exist in the future. So it is considered bad form to put a repository into a POM like that. 

Note that I am not predicting the demise of Bintray, but that Bintray is just another repository, none last forever.

See http://blog.sonatype.com/2009/02/why-putting-repositories-in-your-poms-is-a-bad-idea/ for complete information.

**Comment by edmondo1984** [comment]
+1 When is this planned for?

**Comment by beloglazov** [comment]
+1 would be awesome to have it in Maven central!

**Comment by frgomes** [comment]
+1 Please publish recent versions to Maven Central, including builds for Scala 2.11. Please!

**Comment by xuwei-k** [comment]
+1

**Comment by pchiusano** [comment]
I'm also fine with this.

**Comment by djspiewak** [comment]
It's relatively easy to get something into Maven Central.  The biggest issues are the following:

- [ ] We need to make sure our generated POM metadata conforms to Sonatype standards.  That means things like contributor lists, license information, and stricter schema validation
- [ ] We need to register GPG public keys for anyone who is going to be pushing releases.  I have a public key already registered with Sonatype, but ideally I wouldn't be the only person capable of cutting a release.  :-)
- [ ] We need to present a good argument to Sonatype as to why our artifact name doesn't match our package name
- [ ] We need to present a *substantially better* argument to Sonatype as to why our artifact name does not match a domain that we own (this is usually a sticking point)
- [ ] We need to either configure Bintray to proxy our releases up to Sonatype (this is actually quite easy), or we need to set up the Sonatype workflow directly (this is slightly less easy).

Checking off all thse

**Comment by seratch** [comment]
specs2-core 2.4.x didn't need scalaz-stream dependency. But since specs2 3.0, even spec2-core needs scalaz-stream because specs2-common requires it. 

I know it's also a specs2's issue. However, spces2 and scalaz-stream have leverage in Scala ecosystem. I hope scalaz-stream will be available on the Maven central repository. :+1:

**Comment by etorreborre** [comment]
> Folks hence the current sbt version is using bintray as one of the default repos do you think this is still necessary?

@pchlupacek, I guess you are referring to the ["predefined resolvers"](http://www.scala-sbt.org/0.13/docs/Resolvers.html). Unfortunately, the `bintray` one is just a method `Resolver.bintrayRepo("owner", "repo")`, you still need to specify the `owner` and `repo`.

**Comment by briantopping** [comment]
What if you don't use SBT?

**Comment by haveaguess** [comment]
Yep , this is holding me back on scala 2.10

**Comment by frgomes** [comment]
You can add bintray to your lust of resolvers. It works for me with 2.11.6 :-)
resolvers += "bintray" at "http://dl.bintray.com/scalaz/releases"
Richard Gomes
rgomes1997@yahoo.co.uk
http://rgomes.info/
+44(77)9955-6813
+883(5100)0800-9804
Sent using CloudMagic
On Mon, Mar 30, 2015 at 2:53 pm, Ben Ritchie <notifications@github.com> wrote:Yep , this is holding me back on scala 2.10

**Comment by francisdb** [comment]
or `resolvers += Resolver.bintrayRepo("scalaz", "releases")`

**Comment by briantopping** [comment]
Oh well. It's well known that SBT doesn't get the job done in a lot of circumstances, like IDE integration in purely modular environments. Sad.

**Comment by djspiewak** [comment]
@briantopping Maven and Ivy both support adding external repositories.  Bintray has more instructions ([specifically here](https://bintray.com/scalaz/releases)).  I'm not sure that SBT's inadequacies (or lack thereof) really have anything to do with it.

What build system are you using?  I really can't think of a *useful* build system that allows resolving from Maven Central but provides no mechanism for third-party repositories.

**Comment by briantopping** [comment]
@djspiewak The problem with external repositories in open source is they come and go, as documented before.

**Comment by djspiewak** [comment]
@briantopping I don't dispute that relying on a third-party repo for a critical upstream dependency is bad.  That has absolutely nothing to do with SBT though.

Everyone is basically in agreement that we want to push to Maven Central.  We have to get our ducks in a row first to make that happen though.  It's going to happen.  It's not done *yet*.  The third-party repo dependency is a temporary workaround, where by "temporary" I mean "until we get in Maven Central".  I think I can pretty much guarantee that bintray is going to be around at least until we get in Maven Central.

**Comment by briantopping** [comment]
@djspiewak You're right, I deleted the comment. I saw that a referencing issue was closed and incorrectly believed this one had been closed ten days ago. Apologies for my lack, cheers.

**Comment by haveaguess** [comment]
@djspiewak thanks for making that clear, that's reassuring to see

**Comment by jamesward** [comment]
Requiring devs to add new resolvers is just plain bad developer experience.  Also, libraries in Maven Central aren't supposed to depend on non-Maven Central libraries.  So please get these libraries into Maven Central.  It will take 15 minutes via BinTray.

**Comment by djspiewak** [comment]
@jamesward No one disagrees with you.  This *is* happening; it just has to be Paul that does it.

**Comment by jamesward** [comment]
Cool!  Here is an updated check-list:
- [ ] [Create your JIRA account](https://issues.sonatype.org/secure/Signup!default.jspa)
- [ ] [Create a New Project ticket](https://issues.sonatype.org/secure/CreateIssue.jspa?issuetype=21&pid=10134)
- [ ] [Setup BinTray to Maven Central sync](http://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/)

**Comment by benmccann** [comment]
+1 it'd be nice to make this the top priority of this project. it's quite easy to do and very important for all the reasons already cited

Also, you should never ever ever do `resolvers += "scalaz" at "http://dl.bintray.com/scalaz/releases"` as some comments here are suggesting. You open yourself up to cross build injection attacks. Always use https when adding a repository to your project!

**Comment by xuwei-k** [comment]
> Cool! Here is an updated check-list:
 Create your JIRA account
 Create a New Project ticket
 Setup BinTray to Maven Central sync


Maybe doesn't need `Create your JIRA account` and `Create a New Project ticket`.
scalaz-stream has published maven central in the past
http://repo1.maven.org/maven2/org/scalaz/stream/scalaz-stream_2.10/

**Comment by djspiewak** [comment]
> You open yourself up to cross build injection attacks. Always use https when adding a repository to your project!

…unless you use sbt-gpg and verify your dependencies.

**Comment by benmccann** [comment]
@djspiewak I'm guessing you meant [sbt-pgp](http://www.scala-sbt.org/sbt-pgp/usage.html)?

**Comment by djspiewak** [comment]
@benmccann I did. I just mix up the acronyms. :-)

**Comment by dohque** [comment]
Is it maven central now?

**Comment by beloglazov** [comment]
It would be nice to get it published, as it still causes annoying issues like https://groups.google.com/forum/#!topic/couchdb-scala/IoMBDlz_QlU

**Comment by sksamuel** [comment]
+1 really useful for us at work if this was available on central.

**Comment by aaronp** [comment]
Yes please

**Comment by ern** [comment]
+1 Also ran into this

**Comment by growak** [comment]
+1

**Comment by etorreborre** [comment]
In the light of [this](e53c2b3) it would be nice to do the publication. I'm willing to do it if given the rights to do so.

**Comment by briantopping** [comment]
@etorreborre bad link

**Comment by etorreborre** [comment]
Thanks @briantopping, fixed now.

**Comment by jamesward** [comment]
I've switched many projects from Specs2 to ScalaTest because of this.  So it is hardly one project switching that should make this a priority.

**Comment by djspiewak** [comment]
@pchiusano We can't really leave this outstanding anymore.  I understand that you're very busy.  Is there any way that one of the rest of us could handle this work for you?  We're going on 9 months of this being a "approved, but unimplemented" issue.

**Comment by fommil** [comment]
:+1:

**Comment by pchlupacek** [comment]
@djspiewak I shall have bintray rights. So, if we manage to setup maven/bintray sync somehow we may do this. Not sure what we really needs for this maven sync? Anyone has experience with this?

**Comment by pchiusano** [comment]
I can look at this next week if I'm a blocker on it. I'm pretty deep in
implementing the prototype of the new design at the moment and would like
to get to a better stopping point with that.

**Comment by djspiewak** [comment]
I've published to sonatype before, but only directly and never synced from bintray.  @etorreborre, do you know what's involved here?  I'm pretty sure Sonatype is going to need @pchiusano's sign-off at some point, but I honestly don't know how the sync process works.

**Comment by sksamuel** [comment]
Could you publish to maven separately? Or publish to maven instead - is
there an advantage to being on bintray?

**Comment by pchiusano** [comment]
I am happy to sign off on whatever needs my signing off on... if someone
can tell me what I actually need to do. :)

**Comment by jamesward** [comment]
@pchiusano Good instructions here: http://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/

**Comment by francisdb** [comment]
This might be more up to date: https://bintray.com/docs/usermanual/uploads/uploads_syncingartifactswithmavencentral.html

**Comment by briantopping** [comment]
Artifactory, and JFrog / JCenter by extension, seem very counter to the goals of FOSS. Imagine that folks are successful at somehow making Maven Central into a legacy artifact provider. What happens then?

Between Sonatype and JFrog, I'd pick Sonatype (and Maven Central) any day simply because their repository is open source and their introductory package is free to deploy. JFrog? Not so much.

**Comment by pchlupacek** [comment]
Folks we are in process to publish to maven central. We just need a resolve small issue with access rights. Expect please this to be resolved in week timeframe. Thanks for patience and sorry for delay on this.

**Comment by djspiewak** [comment]
I'm pleased to announce that, as of 0.7.2/0.7.2a, scalaz-stream is now published to Maven Central!  Please open a new issue if you have any problems with this release.

**Comment by jamesward** [comment]
Wahoo!!  Thanks you @djspiewak and @pchiusano.

**Comment by briantopping** [comment]
+1, thanks!

**Comment by frgomes** [comment]
+1 thanks!

**Comment by jbaruch** [comment]
@briantopping lots of questions regarding your comment.
 1. Why you conciser JFrog/Artifactory/JFrog counter FOSS?
 2. I can easily imagine Maven Central as legacy. It already is in terms of features, ease of deployment, REST API, entitlements, stats and logs and what's not. The only thing that keeps it alive is being hard-coded into Maven. Lock-in is not the best strategy to keep being popular. But my perception aside, what horror images of the day Maven Central becomes legacy your imagination pictures? What will happen?
 3. Why would you say that JFrog's repository is not open source and our introductory package is not so much free to deploy?

**Comment by briantopping** [comment]
@jbaruch How about I email you offline and we can post the results here. This isn't really an appropriate venue for a holding a debate.

**Comment by jbaruch** [comment]
Sure thing, please do! jbaruch@jfrog.com. Thanks in advance!
