### ISSUE TITLE
[async.topic] Repeat n messages before a subscriber was run? 

### ISSUE THREAD

**Issue by markfarrell** [scalaz/scalaz-stream#278]
Hi, 

When using async.topic, I would like to be able to send new subscribers the last n items that were published before they subscribed. Is it possible to do this right now? Should/can this be implemented?

**Comment by pchlupacek** [comment]
@markfarrell do you think we can close this issue?

**Comment by markfarrell** [comment]
Sure.

**Comment by pchlupacek** [comment]
Thanks for using library :-)

**Comment by markfarrell** [comment]
No problem - but I've found it somehwat hard to dig up educational resources on scalaz-stream. I feel like there needs to be a more comprehensive guidebook, with exercises, or something.
