### ISSUE TITLE
tcp.writes takes an unbounded ByteVector

### ISSUE THREAD

**Issue by q42mark** [scalaz/scalaz-stream#287]
Hi, 

Just started out with some experiments with scalaz-stream and scalaz-stream-scodec; And I found something curious

The tcp.writes method (and maybe other io related methodes) takes this;

`chunks: Process[Connection,ByteVector]`

The bytevector is not bounded by any size, so it might be possible to send a large bytevector to tcp.writes for example, making tcp.writes buffer up all bytes first?

The scalaz-stream-scodec library uses BitVectors for this. So when using these libs together you should always first run the codec and then call `toByteVector` in order to get the a potentially large bytevector? However I think BitVectors can be large aswell and in essence they come down to the same thing and sequence of bits. 

What are your thoughts on this? Should this cause trouble with large vectors?

**Comment by pchiusano** [comment]
This is as designed. The writes function intentionally does nothing magical so you can chunk your writes in whatever way makes sense for your application, just by transforming the `Process[Connection,ByteVector]` that you pass to `writes`. Certain protocols may need to be very explicit about this - write 10 bytes, then wait for 53 bytes, then write another 12 bytes, etc.

However, I'd welcome a PR with a `bytes` module with some thoughtfully designed functions for rejiggering / chunking / unchunking of `ByteVector` streams. :) I have not thought too much about it, but I'd imagine most can probably be defined using existing `process1` transducers.
