### ISSUE TITLE
Use Scalariform to make formatting more consistent?

### ISSUE THREAD

**Issue by fthomas** [scalaz/scalaz-stream#311]
Is anyone interested in using Scalariform (https://github.com/sbt/sbt-scalariform) to enforce a more consitent source code formatting? You can have a look at how it would reformat scalaz-stream here: https://github.com/fthomas/scalaz-stream/tree/scalariform

**Comment by djspiewak** [comment]
I'm neither a fan of Scalariform's style options nor auto reformatters in general, but that's just my opinion.  I don't mind being forgiving of other people's code style (and thus dealing with some inconsistency) if it means I get to be opinionated about my own.

**Comment by fthomas** [comment]
Thanks for sharing your opinion!
