### ISSUE TITLE
Version 0.7/0.7a

### ISSUE THREAD

**Issue by djspiewak** [scalaz/scalaz-stream#331]
I'd like to request that we start the process to release version 0.7 once we have a resolution to #330 vs #318.  There are several other important fixes which have landed since 0.6, and it would be nice to get them out.  The only other thing I can think of that I want to get into this release is a minor version bump in our scodec/scodec dependency and the appropriate change to `io.toInputStream`.  Basically, @mpilquist exposed a function in `ByteVector` that will make the inner buffering much faster in certain cases.  I'll have that taken care of and PRed this weekend (**update**: PR'd in #332).

**Comment by pchlupacek** [comment]
@djspiewak cool. can we put a list what needs to be done before release? I just created milestone, perhaps we can add just issues to it?

**Comment by djspiewak** [comment]
*Drafting the below mostly from memory and commit log; everyone please feel free to edit this reply*

# Release Notes

## Features

- `io.toInputStream`
- `process1.liftFirst`/`process1.liftSecond`
- `process1.tail`
- `Process#toStream` is now incremental and does not require paging the full process into memory
- Generalized `Sink#toChannel` (now supports arbitrary functors, not just `Task`)

## Compatibility

- Removed `Process#toTask` due to resource unsafety and referential non-transparency (use `step` instead)
- `Process` time functions (e.g. `awakeEvery`) are now in a separate module: `time`
- Deprecated `async.signal` (use `async.signalOf` instead)
- Deprecated `liftIO` (use `toSource` instead)
- Removed `Process.emitSeq` (use `emitAll` instead)
- Removed `Process.emitRange`

### Finalizers

The most significant (and subtle) compatibility change in this release is a revision to the evaluation guarantees and ordering associated with finalizers (e.g. `onComplete`) in the presence of concurrent evaluation and interrupts.  A simple example:

```scala
Process.await(openConnection) { conn =>
  doStuff(conn) onComplete (Process eval_ closeConnection(conn))
} onComplete (Process eval_ putStrLn("done!"))
```

This is a relatively common idiom in resource-heavy code.  Unfortunately, there are some subtle issues here that are hidden by the high-level nature of the combinators.  Let's assume the above process is assigned to the variable `p`.  We might reasonably asynchronously compose `p` with another process in the following fashion:

```scala
p merge otherProcess
```

Now, `merge` (or rather, `wye.merge`) is defined such that if *either* of the constituent processes terminate prematurely with an error, then the other process will be halted immediately.  This is achieved by interrupting any asynchronous work and running all finalizers.  Unfortunately, there is a bit of a problem here: what if `p` is interrupted *during* the evaluation of `openConnection`?

Presumably, the `openConnection` function (which produces something of type `Task[Connection]`) is grabbing a resource that needs to be later released, which is presumably the point to the `closeConnection(conn)` finalizer.  It isn't possible in general to just "stop" this resource allocation process and undo everything that has been done, so this raises a problem in the implementation: do we *ask* `openConnection` to halt and then simply wait for it to finish, or do we ask it to halt and move on *immediately* under the assumption that it will eventually terminate?

The former seems like a good option, except for the fact that `openConnection` may not in fact ever complete!  As mentioned, there is no way to *guarantee* an interrupt on an asynchronous task.  So instead of waiting, we just ask it to halt and then immediately move on with cleaning up the process.  Unfortunately, this leads us to a serious set of complications.

As soon as we have "interrupted" the `openConnection` task, the `merge` cleanup routine needs to make sure that all of the finalizers associated with `p` are invoked.  In this case, we haven't actually completed `openConnection`, so we don't have a value for `conn`, which means that the *inner* finalizer in the example above (`closeConnection(conn)`) cannot be run.  So instead, we just run the `putStrLn("done!")` finalizer and move forward.  Here's the trick though: what if `openConnection` ultimately completes despite our interrupt request?  We now have a `Connection`, which is a resource that presumably we need to free, but we've already moved on with the process, invoked the outer finalizer and otherwise walked away from things.

In previous versions of scalaz-stream, this problem was solved by running *all* of the finalizers, even the ones that had already been run!  Thus, if `openConnection` were interrupted but still completed, then `putStrLn("done!")` would be immediately invoked, followed by later invoking `closeConnection(conn)` and then `putStrLn("done!")` *a second time!*  Thus, finalizers were guaranteed an *at least once* semantic, but this semantic was not particularly well documented, meaning that it was very common to have finalizers which were non-idempotent and could not safely run multiple times.  In fact, scalaz-stream's own higher level nondeterministic utilities included non-idempotent finalizers, and this resulted in occasionally very bizarre behavior and even silent deadlocks.

All of this mess is resolved in scalaz-stream 0.7, but in doing so, the semantics of finalizers have been changed in a very subtle way.  **Be sure to double-check your `onComplete` handlers to ensure that you're not relying on the old behavior!**  Specifically, we now no longer re-invoke previously run finalizers.  Furthermore, we make a hard distinction between an "inner" finalizer and an "outer" finalizer.  An "inner" finalizer is one which is dependent on some resource produced by an `await`, while an "outer" finalizer is outside of an `await` and thus independent of its evaluation.

```scala
Process.await(t) { r => p1 onComplete f1(r) } onComplete f2
```

In the above, `f1(r)` is an inner finalizer, while `f2` is an outer finalizer.  In 0.7, when `t` is interrupted, `f2` will be *immediately* run (just as before) and the process will move ahead.  If `t` completes after interruption and produces a value `r`, then we will invoke `f1(r)`.  We will not re-invoke `f2`.  Thus, `f2` is *guaranteed* to run exactly once, while `f1(r)` will run at most once, and it is *guaranteed* to run if and only if `t` completes.  Notably though, `f1(r)` is run *after* `f2`, despite the fact that `f2` is lexically outside of `f1(r)`.

You will also note that we only make this sort of resource guarantee with respect to finalizers that are *inside* of the `await`!  Thus, the following code is unsound and will leak resources!

```scala
Process.eval(openConnection) flatMap { conn =>
  doStuff(conn) onComplete (Process eval_ closeConnection(conn))
}
```

Notice that the finalizer which releases the resource (`closeConnection(conn)`) is inside of a `flatMap`, and *not* an `await`.  If `openConnection` is interrupted but completes anyway, the entire `flatMap` will be nulled out and the finalizer will not run, despite the fact that we *did* produce a value `conn`.  Finalizers are *only* guaranteed to be safe inside of `await`.

Additionally, multiple nested awaits which acquire paired resources as separate steps (rather than in a single atomic task) can sometimes produce unsound results:

```scala
val a: Lock = ???
val b: Lock = ???

await(a.acquire) { _=>
  await(b.acquire) { _=>
    doSomethingDangerous() onComplete eval_(b.release)
  } onComplete eval_(a.release)
}
```

The problem here is not a question of whether or not the finalizers will all run (they *will* run!), but rather a question of in what order they run.  If we interrupt this process during the evaluation of `b.acquire`, then `a.release` will immediately run.  If `b.acquire` completes despite the interrupt, `b.release` will end up running *after* `a.release`.  Of course, this means that we have released our locks in a different order from the one in which they were acquired, which can lead to deadlocks if the situation is similar across other parts of the code.

The final "gotcha" which can arise with these interrupt semantics becomes apparent if we attempt to fix the above example by merging together the lock acquisition for `a` and `b` by `join`ing the two tasks:

```scala
val a: Lock = ???
val b: Lock = ???

await(a.acquire >> b.acquire) { _=>
  doSomethingDangerous() onComplete eval_(b.release >> a.release)
}
```

On the surface, this seems superior.  However, `Task` is going to interrupt execution of `a.acquire >> b.acquire` as aggressively as it can, which means that if it receives the interrupt during the evaluation of the `a.acquire` step, it will break out of the task before ever running `b.acquire` but still after `a.acquire`!  Even more significantly, `await` will not see the task as having "completed", which means that the `b.release >> a.release` finalizer will *never run* (because the task didn't complete).  `Process` has no way of knowing if a particular critical stage of a given `Task` has completed.  All it knows is whether or not the *entire* `Task` has completed.

Thus, if you're in the habit of acquiring resources with multiple `Task`(s) `join`ed together, each one grabbing a part of the resource, you should probably refactor your code.  `Process` is free to interrupt this sort of `Task` at any point along the way.  The only way you can *guarantee* that your `Task` interrupted atomically is to put all of your resource acquisition within a *single* `Task.delay` or `Task.async` block (`Task.apply` works equivalently).  Splitting a single semantic resource acquisition into multiple `delay` blocks can result in resource leaks.

## Bug Fixes

- Fixed a race condition in `async.signalOf` that could result in deadlocking the thread pool under contention
- Fixed an issue where stepping a drained infinite process could generate infinite recursion in `step`
- Various nondeterminism fixes
  + `wye` sometimes deadlocked on itself while cleaning up halted inputs
  + Reimplemented `runAsync` with new, more precise finalizer semantics (see **Compatibility**)
    * Finalizers will no longer be run multiple times under any circumstances
  + Fixed an issue in `merge.mergeN` which could cause the process to hang if `runAsync` stepped through an empty `emitAll` case
  + Fixed a race condition in `merge.mergeN` which could cause the process to hang under certain circumstances with very rapidly-emitting input processes
  + Leading `Process.await(Task delay { ... })` constructions no longer inhibit concurrent scheduling (fairness) in `wye` and `merge.mergeN`
  + Asynchronous interrupts on `Task` will aggressively terminate the computation as early as possible, presumably improving performance (previously, "interrupted" tasks would *always* run to completion)
- Improved resource cleanup in `Inflater`/`Deflater`

## Known Issues

- The new NIO support (`tcp`) doesn't appear to work correctly

**Comment by fthomas** [comment]
I can't edit your message, but #298 should also be mentioned under **Bug Fixes**:
* Fixed `time.duration` to obtain a new reference time on every `Task` evaluation

**Comment by djspiewak** [comment]
> I can't edit your message, but #298 should also be mentioned

Updated.  Also, should I perhaps stick the release notes in a Gist or a wiki page?  I didn't realize that only contributors could edit messages.

**Comment by fthomas** [comment]
The release notes of past releases are in the scalaz-stream wiki, so its reasonable to also put them there.

**Comment by alissapajer** [comment]
The merge of `master` into `master-a` isn't clean. Are there any objections to just creating a new `master-a` based off `master` and then force-pushing `master-a`?

**Comment by djspiewak** [comment]
Ok, looks like we're good to go for 0.7!  Attention, @pchiusano. Your party would like to meet you at the front desk.

**Comment by alissapajer** [comment]
`master-a` is now updated!

**Comment by pchiusano** [comment]
Sweet. Question - do we want to try to do the release on sonatype? I can also just do a bintray release for now and we can use the same tag / series to do a release on sonatype, in case there is any red tape with that.

A while ago, @fthomas asked me about putting together a CONTRIBUTORS file. I'd like to do that as part of this release. I don't really want to be the one in charge of deciding how to describe everyone's contributions, but was thinking: names listed alphabetically by last name, and each contributor maintains their own one-line description of what they've worked on.

**Comment by fthomas** [comment]
@pchiusano are you still planning to rename the project? From what @djspiewak wrote in https://github.com/scalaz/scalaz-stream/issues/258#issuecomment-77590139 it seems to be easier to rename the project _before_ releasing to Maven Central.

**Comment by pchiusano** [comment]
@fthomas Yeah, though not for 0.7. Also, we still need to come up with a good replacement name. :)

**Comment by pchiusano** [comment]
Also, I am currently on childcare duty so I prob won't be able to cut release until Monday at earliest. :)

**Comment by alissapajer** [comment]
@pchiusano great! We would use a public release as soon as it's available (we're already working off of locally-published jars :) ) so if a bintray release is easier, I'd say we should just go for that first. If/when there's demand for a sonatype release, then that could come second.

I have no preference for the presence of a CONTRIBUTORS file or not, but if there is one, I'd say it makes sense for each developer to just submit a PR adding themself and a tagline to the file.

**Comment by pchiusano** [comment]
Created here:
https://github.com/scalaz/scalaz-stream/blob/master/CONTRIBUTORS.markdown

No need to do PRs if you already have commit access. In fact, if you are
feeling really lazy, you can just edit the markdown directly from the
GitHub site. :)

**Comment by pchiusano** [comment]
Okay, I did the release on bintrary, I'd like to get the release notes cleaned up before announcing, though. Please hold off on any announcements for the time being.

**Comment by alissapajer** [comment]
Awesome :)

**Comment by pchiusano** [comment]
Okay, @djspiewak @alissapajer @pchlupacek @fthomas I cleaned up the release notes page a bit. Could you all take a look through and see if there is anything missing?

https://github.com/scalaz/scalaz-stream/wiki/0.7

Also, @djspiewak can you do a better job of characterizing the issues with `tcp`? And if there are issues, can we get some failing tests added? If you don't have time to do that, I'd maybe just say: "The new `tcp` module should still be considered alpha quality. We've noticed a number of issues with it that we are still tracking down. If you'd like to help make the module production quality, please get in touch."

**Comment by pchiusano** [comment]
Also, @djspiewak on my edits, I tried to succinctly characterize the situations in which the finalization semantics changes is relevant to users (basically resource allocation plus use of nondeterministic functions). That way the person reading can decide to what extent they need to really dig in (like scodec-stream's usage of scalaz-stream doesn't care about any of that). I also moved that long technical discussion to the end, so people can quickly scan the rest of the items.

**Comment by djspiewak** [comment]
@pchiusano On the issues with `tcp`, I did file a long issue which contains (as I recall?) three sub issues.  I would break things down into two categories:

- The type signatures are wrong, and satisfying those signatures internally results in incorrect (or at the very least, unexpected) semantics.  `tcp.server` taking a concurrency bound and then still returning a nested process is the best example of this.
- The existing tests mostly don't work, and appear to have only worked in the past due to thread scheduling vagaries (e.g. the fact that leading `Suspend` blocks used to be run *nonconcurrently*).  You can take a look at the changes I made just to get the `bug/step` branch running.  In a sense, you can actually treat the existing tests as "failing tests", since I directly disabled functionality in the tests in order to make them work.

Anyway, the issue I filed has a lot more details.  I'm fine with just saying "should be considered alpha quality".  I just wanted to get a warning in the release notes, since people might be looking at using it in its current state, which I don't believe would be the best idea.  I do plan on working on the `tcp` stuff in this next release cycle.  It's a little lower on my priority list than optimized chunk processing and `onComplete` soundness, but it *is* on my list.

On a completely separate note, I'm pretty sure that the `close0` hang in the NIO2 support on Mac is actually a bug in Darwin, based on the effect it has on the process image and the way that the JDK implements that function.  So that sort of sucks, because it means our odds of fixing it are pretty low.

**Comment by alissapajer** [comment]
@pchiusano Just read through the release notes and added a couple things. Looks good to me.

**Comment by fthomas** [comment]
I added the `Process1Syntax.contramap` and the typeclass instances for Process1. LGTM

**Comment by djspiewak** [comment]
@pchiusano Are we green for tweeting/etc about 0.7?

**Comment by pchiusano** [comment]
Standby, I will send an email to the scalaz list which you can link to if
you like.

**Comment by pchiusano** [comment]
Okay, fire away: https://groups.google.com/forum/#!topic/scalaz/sKMmvVChK08

**Comment by djspiewak** [comment]
0.7/0.7a is released and we're all shouting about it.  I'm going to close this issue.

Thanks so much for cutting the release, Paul!  I know I'm super-psyched for the changes.

**Comment by fthomas** [comment]
> Also, we still need to come up with a good replacement name.

Can we do something about this? Like opening an issue where people can post their suggestions? Or anything else?
I'd love to see scalaz-stream getting a new name sooner rather than later.
