### ISSUE TITLE
Add a dequeueBatch function to async.queue

### ISSUE THREAD

**Issue by djspiewak** [scalaz/scalaz-stream#338]
Implement a `dequeueBatch: Process[Task, Seq[A]]` which dequeues *all* values currently backed up in the queue, or "continuation blocks" (the same as with `dequeue`) when no values are available.  No hysteresis or delay buffer is expected here.  Thus, if no values are in the queue, and a value is added, singleton sequence would be *immediately* reported.  However, if during the processing of that chunk, more than one element were enqueued, the *next* element of the `dequeueBatch` stream would be a multi-element sequence.

**Comment by pchlupacek** [comment]
@djspiewak cool idea. Would be nice if we add `max` parameter to it tho, to still have sort of control over fairness. Wonder if we really can't implement some work stealing here, but likely not....

**Comment by djspiewak** [comment]
@pchlupacek I tend to think of fairness as something that is controlled in `wye` and `njoin`, but you're right that it is a concern here as well.  A `max` parameter seems appropriate.

I can't think of any direct way to implement work stealing.  `Queue`'s contract is to dump values into a single, *sequential* consumer.
