### ISSUE TITLE
Rename WriterSyntax.drain{W,O}?

### ISSUE THREAD

**Issue by fthomas** [scalaz/scalaz-stream#344]
`Process.drain` is defined as
```
def drain: Process[F, Nothing] = flatMap(_ => halt)
```
while `WriterSyntax.drainW` and `WriterSyntax.drainO` are defined as
```
def drainW(snk: Sink[F,W]): Process[F,O] = observeW(snk).stripW
def drainO(snk: Sink[F,O]): Process[F,W] = observeO(snk).stripO
```
IMO this is unfortunate because `Process.drain` suggests that those two are more like
```
def drainW: Writer[F, Nothing, O] = self.flatMapW(_ => halt)
def drainO: Writer[F, W, Nothing] = self.flatMapO(_ => halt)
```
which are useful functions on their own I'd like to add later. Should we rename `drainW` and `drainO`? What would be better names for them?

**Comment by fthomas** [comment]
Or maybe `Process.drain` should be renamed? What about calling it `ignore` instead? We then could have `ìgnoreO` and `ìgnoreW` for `Writer`.

**Comment by alissapajer** [comment]
@fthomas I like the name `Process.drain`, but I do agree that that naming scheme is inconsistent with how "drain" is used in `WriterSyntax`. 

How about renaming `drainW` and `drainO` in `WriterSyntax` to `observeStripW` and `observeStripO`?

**Comment by fthomas** [comment]
I'm ok with `observeStripW` and `observeStripO`. If there are no other suggestions, I'll submit a PR that renames those two.

**Comment by pchlupacek** [comment]
another option is to keep drain as it is, and rename them to `drainObserveW` and stripW rename to simply `drainW`. That way perhaps we have consistent naming between process and writer

**Comment by fthomas** [comment]
`drain` discards all outputs of a `Process`. I would expect that `drainW` discards all outputs on the write side of a `Writer`, so `drainW: Writer[F, W, O] => Writer[F, Nothing, O]`. I've recently used something like `drainO` to strip the outputs of a `Writer[F, W, Unit]` and then to append it to some other `Writer[F, W, O]`. If `drainO` would have transformed the `Writer` into an ordinary `Process`, an additional `liftW` would have been required there.

**Comment by pchlupacek** [comment]
Ah, I see what you say. Then I don't have any preference. Perhaps only, that instead introducing `observeStripW` I can live with observeW().stripW as this is only two letter more and it is more explicit what it really does and allows me to combine `O` and `W` freely.

**Comment by fthomas** [comment]
This is also fine for me. I'll put a PR together to make things more concrete.
