### ISSUE TITLE
Disallow race condition while using signal

### ISSUE THREAD

**Issue by pchlupacek** [scalaz/scalaz-stream#347]
Current signal constructors allow to create race programs, that may not be obivous to user. We need to clear signal interfaces to eventually not allow these conditions. 

Currently, we have two constructors of signal: `signalOf` and `signal` (deprecated). There is a race condition using signalOf to lose first value (possibly more, but first is almost guaranteed) set: 

```scala 

  property("signalOf.init.value") = secure {
    val timer = time.sleep(1.second)
    val signal = async.signalOf(0)

   (eval_(signal.set(1)) ++ signal.discrete.once ++ timer ++ signal.discrete.once).runLog.run ?= Vector(1,1)
  }

```

I think we have to either change `signalOf` implementation to not use `toSignal` and rather do initial value with passing initial `W` in implementation `writer1`. 

Essentially any Signal that is fed from upstream shall not be settable with `set`, `compareSet` etc. Similarly the signal created to be set from `downstream` shall never receive any values from upstream. 

@djspiewak  any thoughts on this?

**Comment by djspiewak** [comment]
It actually surprises me quite a bit that this generates a race condition.  It appears that the topic inside of `Signal` makes itself available before it has flushed through the init process.  In other words, the sane assumption about `toSignal` doesn't hold.

I think we actually need to fix `Signal` to hold incoming messages until `inits` has been fully `unemit`ed.  This would also fix the identical race condition in `toSignal`.

**Comment by pchlupacek** [comment]
I just put that PR. I don't think so its good tenchnique to have merging semantics hardcoded in `Signal`. I think we have either signal that is set by evaluating Tasks ( I call this downstream signal) or, eventually is constructed by "upstream" process. I think both of them shall not be in our code w/o involving nondet combinator like `wye`
