### ISSUE TITLE
Transducers to generalize Process1

### ISSUE THREAD

**Issue by djspiewak** [scalaz/scalaz-stream#351]
```scala
  sealed trait AcceptT[+F[_], -I, +O]

  object AcceptT {
    trait Partial[F[_], I] {
      type Aux[α] = AcceptT[F, I, α]
    }

    final case class Effect[+F[_], O](f: F[O]) extends AcceptT[F, Any, O]
    final case class Accept[+F[_], I]() extends AcceptT[F, I, I]
  }

  type Transducer[+F[_], -I, +O] = Process[AcceptT.Partial[F, I]#Aux, O]
  // type Process1[-I, +O] = Transducer[Nothing, I, O]
  // type Channel[+F[_], -I, +O] = Obsolete!!
  // type Sink[+F[_], +A] = Transducer[F, A, Unit]

  object transducer {

    def receiveF[F[_], A, I, O](effect: F[A])(f: A => Transducer[F, I, O]): Transducer[F, I, O] =
      await[AcceptT.Partial[F, I]#Aux, A, O](AcceptT.Effect(effect))(f)

    def receive1[F[_], I, O](f: I => Transducer[F, I, O]): Transducer[F, I, O] =
      await[AcceptT.Partial[F, I]#Aux, I, O](AcceptT.Accept[F, I]())(f)
  }

  implicit class TransducerSyntax[F[_], A](val self: Process[F, A]) extends AnyVal {
    import Cause.{EarlyCause, End, Kill}

    def transduce[B](trans: Transducer[F, A, B])(implicit F: Applicative[F], C: Catchable[F]): Process[F, B] = trans.suspendStep flatMap {
      // fail suck ugliness to get around limitations in GADT pattern matching
      case Halt(rsn) => self.kill onHalt { _ => Halt(rsn) }

      case step: Step[AcceptT.Partial[F, A]#Aux, B] => {
        val cont1 = step.next

        step.head match {
          case awt: Await[AcceptT.Partial[F, A]#Aux, a, B] => {
            val req = awt.req
            val rcv = awt.rcv

            req match {
              case AcceptT.Effect(eff) => {
                val fp = eff.attempt map { _ leftMap { Error(_) } } map { res =>
                  self transduce (cont1.+:[AcceptT.Partial[F, A]#Aux, B](rcv(res).run))    // TODO errors?  I don't have access to Util.Try, because... blergh
                }

                eval(fp) flatMap { a => a }
              }

              case AcceptT.Accept() => self.step match {
                case Step(awt @ Await(_, _), cont) => awt extend { p => (p +: cont) transduce step.toProcess }

                case Step(Emit(Seq()), cont) => cont.continue transduce step.toProcess

                case Step(Emit(is), cont) => {
                  val nextT = cont1.+:[AcceptT.Partial[F, A]#Aux, B](rcv(\/-(is.head.asInstanceOf[a])).run)      // this is sound because Accept proves it so
                  val nextS = emitAll(is.tail) +: cont

                  new TransducerSyntax[F, A](nextS) transduce nextT
                }

                case hlt @ Halt(End) => new TransducerSyntax[F, A](hlt) transduce (step.toProcess disconnect Kill swallowKill)
                case hlt @ Halt(rsn: Cause.EarlyCause) => new TransducerSyntax[F, A](hlt) transduce (step.toProcess disconnect rsn)
              }
            }
          }

          case emt @ Emit(os) => {
            emt onHalt {
              case End => self transduce cont1.continue
              case early => self transduce (Halt(early) +: cont1) causedBy early
            }
          }
        }
      }
    }
  }
```

I have some comments to this effect, but basically `Transducer` completely subsumes `Process1` and provides a strictly more powerful construct to replace `Channel` and `Sink`.  As mentioned in the gist, `Process1[A, B] = Transducer[Nothing, A, B]`, which is pretty cool!

Here's the motivation…  `Channel` allows us to define an effectful transformation on some input `Process`.  However, unlike with `Process1`, it is not possible to define a `Channel` as some sort of state machine based on input!  The transduction input elements to a `Channel` are received by the inner composite function.  If the enclosing effect is `IO`-like, it is possible for a function to *mutate* some register to change what function "comes next" based on the input observed, but outside of this sort of spooky action, it isn't possible.

By comparison, `Process1` makes it very very easy to define a state machine on the input stream.  That is in fact the whole purpose of `Process1`!  `Transducer` generalizes this notion and allows us to define a state machine on an input stream…while still embedding effects!  This greatly expands the space of possible effectful transformations that can be conveniently encoded, and completely obsoletes both `Channel` and `Sink` (well, `Sink` would be a transducer, but you get the idea).

Here's the catch…  As with monad transformers, Scala isn't too happy inferring certain chained type constructors.  You'll notice some consequences of this in the implementation above.  Specifically:

```scala
self transduce (cont1.+:[AcceptT.Partial[F, A]#Aux, B](rcv(res).run))
```

Obviously this is ugly.  The problem is that Scala is unable to *infer* the correct type parameters for `+:`.  Originally I thought that this was just a problem with `+:` and `Cont`, but unfortunately it also extends to much more useful combinators.  Like, for example, `++` on `Process`.  And before you ask, no, variance doesn't have anything to do with the problem.  I have a [relatively minimized case](https://gist.github.com/djspiewak/ac9af4519f65c6e5ad01) with no variance or subtyping of any kind.

Anyway, as with monad transformers, the solution here is to punt the problem over to implicit resolution (similar to `scalaz.Unapply`), which gives us some control over the type constructor inference.  I'm still working on sorting this part out, but I have no doubt that it will work.  Hat-tip to @milessabin for putting me on to that solution…

Here's the catch…  In order to make this work, in order for us to have this really nice generalization to unify *all* of our stream transducers into a single framework, in order to enable straightforward definition of *effectful* state machines on input streams (very desirable!), we need to adjust some type signatures.  Most notably, `++` is going to need to take an implicit parameter which performs the type constructor inference.  In a sense, `append` would get removed and replaced with `appendU` (think: the `U` variants of certain functions in Scalaz).  This significantly complicates our type signatures and does break binary compatibility.  Everything should infer nicely though, regardless of whether we're using `Transducer` with `++` or just a plain-old `Process[Task, _]`.  So it wouldn't change *call-site syntax* at all, just the raw types.

Are there any thoughts on this?  @pchiusano?

**Comment by pchiusano** [comment]
I did some playing around with this sort of design, where effectful channels become the primary data type and `Process1[A,B]` is a `Process[Nothing,A,B]`. I do suspect it is a better design for the library, but it may be a lot of work to implement, especially if we want to preserve constant-time append and flatMap.

Here is an old gist I did (in Haskell) https://gist.github.com/pchiusano/bdf7549ef8eb3a32d674 and I also ported a type-aligned sequence type to Scala: https://gist.github.com/pchiusano/3162dadd37cf2211bb44

I haven't thought too much about inference but the way I was thinking of implementing I doubt any unapply tricks are needed.

**Comment by djspiewak** [comment]
@pchiusano Oh, I think in my excitement over type issues, I may have skated over runtime stuff…  What I pasted in the OP works.  As in, it compiles as written and runs and provides exactly the functionality advertised.  In terms of performance characteristics, it should be exactly as fast as `pipe`, which is to say slower than `flatMap` and a heck of a lot slower than `append`, but about as fast as one would expect for a fuser.

So in other words, the "lot of work to implement" is already done.  :-)

The only reason that the unapply tricks are needed is because I needed to throw an extra type constructor around the effect.  This was needed because `Await` is being functionally overloaded for transduction.  In one case, `Await` represents an effect to be performed, with the value of an existential type passed to the receiver.  In the other case, `Await` represents a value coming directly from the fused incoming stream.  `Process[F, A]` can only represent the former case, and `Process1[I, O]` can only represent the latter.  Representing both at the same time requires a type constructor which wraps around `F[_]` while still providing the functionality of `Env#Is`.  This is `AcceptT` in my formulation.

The unapply tricks come into the fray due to the fact that `AcceptT` is a type constructor wrapped around a type constructor.  Scalac's inference simply bails out whenever it hits a type which has that shape.  It's not even "inference in the context of subtyping" or "inference unifying two processes of different effect types" or even "inferring a proper variable binding type from an expression".  It's a problem that manifests just inferring a plain-old polymorphic argument type to a function, so in short, one of the simplest inference problems.

Since the "type constructor wrapping around a type constructor" thing seems pretty fundamental, and yet this is *exactly* the case that scalac just immediately bails on, I think we're going to be stuck with an unapply-like construct gracing our type signatures if we want this sort of functionality.

**Comment by milessabin** [comment]
FWIW, an implicit- rather than GADT-based type aligned sequence would be dramatically simpler than that I think. Ping me if it's still relevant and you need a hand.

**Comment by pchiusano** [comment]
@milessabin PING :) Could you elaborate on your remarks? Maybe put together a gist of just a type-aligned cons list, in the style you think would be simpler.

**Comment by milessabin** [comment]
Just to be sure ... we're talking about is essentially a list of functions which are statically guaranteed to compose? What's the minimal set of operations you'd need defined for it?

**Comment by pchiusano** [comment]
@milessabin Well, not necessarily functions, a list of arbitrary `K[_,_]`. And we need cons/uncons/append. Cons has the obvious signature, and uncons needs to return either the empty sequence, along with a proof that the starting type is equal to the ending type, or it needs to return the `(K[A,e], TList[e,B])` pair, where e is existential. Cons and uncons should both run in constant time.

In order to implement all the operations efficiently, I believe we really do need the sequence itself rather than some church-encoded version of it.

**Comment by milessabin** [comment]
Can you sketch out the operations you want to perform at a slightly higher level? I'm somewhat skeptical that you really need an uncons of that exact form (especially the existential part of it) but to be sure of that I need a rough idea of the kinds of things you would want to implement in terms of it.

**Comment by pchiusano** [comment]
@milessabin Well, for the implementation of `pipe`, `tee`, and `wye`, we need to be able to step the process, and obtain the first emitted chunk in constant time. But we also need to be able to append and flatMap in constant time to build up a Process. And there may be cases where we are alternating between building up a process and consuming it one step at a time, so CPS'ing won't be efficient. If you read the [Reflection without remorse](http://homepages.cwi.nl/~ploeg/papers/zseq.pdf) paper they do a good job of explaining the problem.

Maybe you can illustrate the general gist of what you are thinking for some simplified set of operations, and I can figure out if it is applicable to the stuff we are doing. Like how about assume `cons`, `append`, and `kseq` (below) for now? I should be able to get the idea from that:

```Scala
trait TList[K[_,_],A,B] {
  def append[C](tl: TList[K,B,C]): TList[K,A,C]
  def cons[A0](hd: K[A0,A]): TList[K,A0,B]
  // don't feel like encoding this higher-rank type into Scala, but you get the idea
  def kseq[F[_]:Monad](eval: forall a b . K[a,b] => (a => F[b])): A => F[B]
}
```

**Comment by milessabin** [comment]
That `kseq` has to be linear time, surely?

**Comment by pchiusano** [comment]
Yes. But I more just want to understand what you are thinking about how to encode these sorts of things without GADTs. The exact set of operations isn't so important.

**Comment by milessabin** [comment]
Oh, sure. I'd encode it as a heterogenous sequence structure along with a proof that the required alignment property holds. An `HList` obviously doesn't give you constant time append, but we could use a structure other than a cons list as the underlying carrier. Your `kseq` is essentially a polymorphic fold ... the one in shapeless is linear time and that should carry over here.
