### ISSUE TITLE
There's no link to API doc from project root page?

### ISSUE THREAD

**Issue by toby5box** [scalaz/scalaz-stream#356]
Is this just an oversight?

**Comment by fthomas** [comment]
The docs for the latest release are not published anywhere. We haven't decided yet where and how to publish them.

**Comment by jedws** [comment]
they could [should?] be published as github pages. for instance scalaz
publishes

http://scalaz.github.io/scalaz/

and puts its latest release docs are here:

https://oss.sonatype.org/service/local/repositories/releases/archive/org/scalaz/scalaz_2.11/7.1.1/scalaz_2.11-7.1.1-javadoc.jar/!/index.html#scalaz.package

if you do use github pages, pick a prettier default than scalaz would you
please :-)

https://pages.github.com/

cheers,
jed.

**Comment by djspiewak** [comment]
@jedws Seems like if we just push to Sonatype, we'll be able to link in the same way that Scalaz does with or without GitHub Pages, no?

**Comment by jedws** [comment]
Daniel, that seems like it should work, yes, but I am not certain.

**Comment by xanderdunn** [comment]
I'd also love to see this.  I've been using [this](http://www.jeffshaw.me/scalaz-stream/0.8/#package) for now, which I just saw posted on the Gitter.

**Comment by pchiusano** [comment]
This is done, closing.

**Comment by xanderdunn** [comment]
@pchiusano Fantastic!  Thanks!
