### ISSUE TITLE
wye.interrupt isn't reliably interrupting

### ISSUE THREAD

**Issue by djspiewak** [scalaz/scalaz-stream#362]
Still tracking this down, but it appears to be something related to when the signal process is *killed* rather than producing `true`.  This is of course a major problem for `njoin`, which does precisely this all the time.  The case I have reproducing this locally (still working on more minimization) is a `mergeN` where the inner processes are themselves `mergeN`, and one of the composite processes within this inner `mergeN` dies with an `Error`.

**Comment by edwinchoi** [comment]
`nondeterminism.njoin` has the same problem that `wye` did in #316. I suspect that is the issue here.

**Comment by djspiewak** [comment]
@edwinchoi So you think this might be related to #353? Perhaps `njoin` is receiving multiple finalizer calls as a result of that bug, and then hanging for the same reason as #316?

**Comment by pchlupacek** [comment]
@djspiewak I agree with @edwinchoi that njoin has simillar behaviour to wye, that means if mulitple finalizers were invoked njoin will just call them. We have to perhaps modify njoin similarly as wye.

**Comment by djspiewak** [comment]
@pchlupacek I think we should modify `njoin`, but also finalizers shouldn't be running multiple times.  I'm working on the finalizer thing right now.  @edwinchoi, how hard do you think it would be to contrive a minimal case which breaks `njoin` in this way?  I have a very non-minimal one, but since you have a firmer grasp on the problem than I do, I was wondering if it would be straightforward for you to just contrive one bottom-up.

**Comment by alissapajer** [comment]
@djspiewak @edwinchoi @pchlupacek  I was able to grab an example from #316 and use `merge.mergeN` instead of `wye.merge` to reproduce the issue.

On latest master, this times out. 

```scala
object Test extends App {
  import scalaz.stream._
  import Process._

  implicit val scheduler = DefaultScheduler

  for (i <- 1 to 100) {
    println(s"run $i")
    val q = async.unboundedQueue[Unit]
    q.enqueueOne(()).run

    val process = (merge.mergeN(0)(Process(q.dequeue, halt)).once wye halt)(wye.mergeHaltBoth)
    process.run.timed(3000).run
    println("done")
  }

  println("all done")
}
```

The version that doesn't time out (using `wye.merge`) substitutes in the following line:

```scala
val process = ((q.dequeue merge halt).once wye halt)(wye.mergeHaltBoth)
```

**Comment by alissapajer** [comment]
Important to note: the example case I just posted above is looping 100 times and often does not hang during the first few loops. Of four runs I just ran, it has hung on loop #s 43, 8, 71, and 2. So, if you're not seeing it hang, try increasing the number of loops :)
