### ISSUE TITLE
Change all specs to be classes instead of objects

### ISSUE THREAD

**Issue by pchlupacek** [scalaz/scalaz-stream#363]
Current object specs are subject of object initialization deadlock in certain concurrency scenarios. we just need to convert our specs to be classes to fix this. 

Any volunteers to make PR with object -> class refactoring on all our specs are welcomed :-)

**Comment by alissapajer** [comment]
done. PR incoming.

`$ sed -i .bak 's/object \(.*\)Spec/class \1Spec/' src/test/scala/scalaz/stream/*`
