### ISSUE TITLE
Request: Switch to managing versions with sbt-git

### ISSUE THREAD

**Issue by djspiewak** [scalaz/scalaz-stream#367]
This is a bit of a meta feature request, but I'd like it if we could switch our build over to managing versions  with [sbt-git](https://github.com/sbt/sbt-git).  The reason being that we (@alissapajer and myself) really need to be able to have repeatable builds that point to snapshots of scalaz-stream (which I usually push to my personal bintray), and this is not possible with the current snapshot scheme.  Our solution thus far has been to `set version := ...` where "…" is some function of the git hash, but this is an unnecessarily tedious solution.  sbt-git is extremely nice and it completely deletes all of those "updating to next version" commits that are part of almost everyone's release process (including our own).

Thoughts needed from @pchiusano on this one.  The only major thing that would be different in the release process is, rather than manually changing `build.sbt` to have a new stable version, you would create a git tag for the new version (e.g. `release/0.7`) and then reload your SBT instance.  When a commit is pointed to by a tag which matches the release spec, the `version` property is updated to match.

Anyway, this would make my life a *lot* easier, it would make our commit log cleaner in the presence of releases, and I think it would make @pchiusano's life easier too.  High fives all around?

**Comment by runarorama** [comment]
I would like to second this motion.

**Comment by pchiusano** [comment]
+1!! Can someone take the lead on this. Definitely no objections from me.

**Comment by djspiewak** [comment]
@pchiusano You had me at hello.  :-)

PR incoming…
