### ISSUE TITLE
Queue can lose data in error cases

### ISSUE THREAD

**Issue by djspiewak** [scalaz/scalaz-stream#372]
Hurray!  Just what everyone wants to wake up to, am I right?

```scala
  property("dequeue.preserve-data-in-error-cases") = forAll { xs: List[Int] =>
    val q = async.unboundedQueue[Int]

    val setup = for {
      _ <- (Process emitAll xs to q.enqueue run)
      _ <- q.close
    } yield ()

    val driver = q.dequeue to (Process fail (new RuntimeException("whoops")))

    val safeDriver = driver onHalt {
      case Error(_) => Process.Halt(End)
      case rsn => Process.Halt(rsn)
    }

    setup.run

    val results = (safeDriver merge q.dequeue).runLog.run
    (results == xs) :| s"got $results"
  }
```

This fails, as you can probably guess by the title of this issue.  Example output:

```
[info] ! queue.dequeue.preserve-data-in-error-cases: Falsified after 3 passed tests.
[info] > Labels of failing property: 
[info] got Vector()
[info] > ARG_0: List("0")
[info] > ARG_0_ORIGINAL: List("613002237")
```

Actually what's really weird is it *isn't* the first element that gets lost!  I have no idea why, but it appears to be the second element, if one exists.  Very strange…

Anyway, this is arguably yet another casualty of #288.  At least at first glance it seems to be.  We pull the value off the queue and hand it off to `tee`, but in interpreting the `Await` which results from this merger we hit an error, which causes `tee` to kill off the `dequeue` and *drop the data on the floor.*  This last bit is the scary part.

We need to put it back on the queue.  It's really really important that we have the opportunity to recover from issues like this.  Of course, this does mean that our queues will have a slightly elastic bound (in worst case, up to double the requested bound), since more data may have entered the queue in the meantime, but this is dramatically preferable to simply losing the data entirely.

**Comment by pchlupacek** [comment]
@djspiewak my first thoughts for this is that this is direct result of queue feeding the interrupted tasks. I think the only stable solution to this is to never feed the item to the task that was interrupted. So back to our discussing elsewhere cb == `Throwable \/ A => Boolean` instead of current Unit. The last think I would ever want in this situation is to re-queue the missed element thus having the disordered elements.

**Comment by djspiewak** [comment]
Please note that the junction is a tee and not a wye. The task is not
getting interrupted (this is relatively easy to check by peeking into
stepAsync).  The task runs to completion, hands off its data, and then the
data is discarded by tee due to the error state on the other side.

We have access to the vector inside of Queue.  It is very easy to requeue
preserving original order.  I actually have an implementation in mind for
this (yay sleep-coding) which I will elaborate on later today if it works
the way my brain compiler says it should.

**Comment by pchlupacek** [comment]
ok cool

**Comment by djspiewak** [comment]
@pchlupacek The implementation in the PR really quite straightforward.  Each `ConsumerRef` now tracks its last-dequeued batch.  If a consumer ends prematurely (i.e. before the queue is closed), we re-enqueue the data at the head of the queue (by prepending to the `Vector`).  If the queue is empty, we delegate to `enqueueOne`, which will push the data over to any awaiting consumers.  Caveats of the implementation are detailed in the PR.
