### ISSUE TITLE
Cut support for Scalaz 7.0.x

### ISSUE THREAD

**Issue by djspiewak** [scalaz/scalaz-stream#388]
Scalaz 7.2 is coming soon, and we're still only supporting 7.1 as a "forward port" merge branch.  I don't think there's any question that going to 7.1 as a primary branch is going to be annoying due to the requisite `@uncheckedVariance` that we'll need EVERYWHERE, but I really don't think there's any ongoing value in maintaining the 7.0 branch at all.  Besides, we're going to need to free up branch space to forward-port for 7.2.

Speaking of which, going forward, I'd like our primary development branch to track the most recent version of our upstream dependencies, with the off-branch (currently `master-a`) tracking the backports.

**Comment by pchlupacek** [comment]
+1

**Comment by pchiusano** [comment]
Also +1
