### ISSUE TITLE
`Process#runLog` ascribes `c.i.IndexedSeq` as `c.IndexedSeq`

### ISSUE THREAD

**Issue by refried** [scalaz/scalaz-stream#392]
The latter (non-immutable `IndexedSeq`) doesn't have a scalaz instance.  Could we let the return type be `Vector` or `immutable.IndexedSeq` instead, which do?

**Comment by djspiewak** [comment]
I see no reason why we *shouldn't* do this.  `Vector` is the only practical `IndexedSeq` implementation anyway.  Care to push up a PR with this change?

**Comment by refried** [comment]
Oops, I made the change and then came back here to realize that I didn't know whether you meant change it to `c.i.IndexedSeq` or to `c.i.Vector`; I ended up going with the latter because its scalaz instance is less complicated.  Let me know if you'd like me to change it around though.

**Comment by djspiewak** [comment]
@refried I'd rather make it specifically `c.i.Vector`, so I think we're good!
