### ISSUE TITLE
Pipe won't chain correctly cleanups 

### ISSUE THREAD

**Issue by pchlupacek** [scalaz/scalaz-stream#421]
Given the following code 
```scala

 property("receive1Or") = secure {

    lazy val p1a:Process1[Int,String] =
      receive1Or[Int,String](emit("A")){ i =>
        emit(i.toString) ++ p1a
      }

    lazy val p1b:Process1[String,String] =
      receive1 {
        case "2" => emit("2")  //note that the process terminates here
        case other => emit(other) ++ p1b
      }

    lazy val p1c:Process1[String,String] =
      receive1 {
        case "2" => emit("2") ++ p1c  //note we recurse here
        case other => emit(other) ++ p1c
      }

    val result =
      Process(1,2).toSource
      .pipe(p1a)
      .pipe(p1b)
      .runLog.run

 
    println(result)
    result ?= Vector("1","2","A")
  }

```

Shall produce `Vector(1,2,A)` but instead produces just `Vector(1,2)` . If we remove ` .pipe(p1b)` or just replace it with ` .pipe(p1c)` the output is as expected. 

This indicates `pipe` is not handling correctly the normal termination of the right side, where it won't consult the left side fallback in that case.

**Comment by pchlupacek** [comment]
@djspiewak I am not sure completely, if this is bug at all, or just odd behaviour. I hit that behaviour when working with writers having deep pipeO/pipeW/stripW/stripO structure, where it wasn't obvious the last process just din't had the recursion. To me this can be just `behaviour` of incorrectly combined processes, but perhaps you will see a way how to prevent these kind of errors... :-)

**Comment by djspiewak** [comment]
@pchlupacek I'm about 99% certain that it's just weird behavior.  The key to this certainty is the fact that `A` is emitted as the last element of the stream that results from piping through `p1a`, but that last element comes *after* `2`!  In other words, `p1a` is working just fine in that `A` is emitted at the tail end of *its* input stream, but `p1b` wipes that out by pruning off everything that follows `2`.

Basically, the termination handling in `Process1` nests and does not "bubble up" to the outer level.  I would argue that the semantics as they stand are the most consistent possible, it just seems a bit weird at first glance.  You *might* be able to get `A` to emit by nesting the `p1b` pipe onto `p1a`.  Like so:

```scala
    val result =
      Process(1,2).toSource
      .pipe(p1a.pipe(p1b))
      .runLog.run
```

I'm not certain that this will emit `A`, but it seems probable.

**Comment by pchlupacek** [comment]
yeah I do have same explanation. I am trying to corner that in Writer scenarios, the case I minimised in example seems clear, and of course when you see it is quite obvious that p1b essentially caused the p1a to stop any further evaluation. In more complex scenarios with writers however that reasoning may not be that obvious, specifically if you have stripW/O in the chain. 

I think behaviour is correct in fact and as expected. Of the later process terminates early there is no way for the left processes to pipe any more values to the p1 that is in halt state. 

I am just actually closing this. Thanks for your time on this one. 

P.
