### ISSUE TITLE
Pick new name for project

### ISSUE THREAD

**Issue by pchiusano** [scalaz/scalaz-stream#428]
With the project core shedding its scalaz dependency in a future release, it deserves a new name. Here's what we will do:

* Brainstorm and discussion on this thread until end of this week. Anyone may submit ideas.
* All contributors who care to participate - by end of this weekend, let me know your thoughts on the submissions. If you could flag a "favorite" and any that you absolutely hate, that would be helpful.
* I will select a winner, let's say sometime next week.
* This is not going to be a democratic vote. I'll take people's suggestions seriously, especially from core contributors, and would like to find a name people like (or at least don't hate), but it'll be me who picks the name. :) If you have strenuous objections to this process, raise them here or send me a private email.

Don't go crazy debating names here. State your preferences if you have any, and if you want maybe a sentence or two why.

**Comment by levinotik** [comment]
How about "spout" as in emitting/discharging something in a stream?

**Comment by pchiusano** [comment]
Noted! @djspiewak, @pchlupacek, @alissapajer, @fthomas, @runarorama or anyone else? I was expecting a deluge of suggestions. :)

**Comment by milessabin** [comment]
"deluge" ;-)

Slightly more seriously, how about "Bachle" (which I guess English speakers could rhyme with "tackle")? See [Freiburg Bächle](https://en.wikipedia.org/wiki/Freiburg_B%C3%A4chle).

**Comment by alissapajer** [comment]
"pipes"
"structures" or "structs"
"flux"
"flows"

From those four, "flux" would be my favorite.

**Comment by pchlupacek** [comment]
How about Aqueduct?

**Comment by pchiusano** [comment]
Here a various ideas I've thought of:

Stuff based on some stream-like imagery or metaphor: flux, flow, spout, cascade, surge, etc. I haven't really liked any of these that I've thought of. Of these, agree with @alissapajer Flux is probably the one I like best so far. Scala Flux.

A couple variations on adding a mostly random letter to the word stream: fstream, streamf, f-stream, stream-f ('f' for 'effectful'), or z-stream, stream-z, streamz, zstream. I like the 'z' variations as a bit of an homage to the library's scalaz roots, and they also sound kinda cool to me.

I put together a [logo template here](https://docs.google.com/drawings/d/1p17CpkL__JS2FopAIygGm5U-otBE4MxC8jj0IKOPEoQ/edit). Pretty much anything you put in for the name looks pretty cool IMO. Here's [stream-z](https://docs.google.com/drawings/d/1bYKRU-ZNwgBaOg-XrQH_tbrivjPaSDh7VAZngInZmyM/edit?usp=sharing).

**Comment by pchlupacek** [comment]
I wonder with flux we may have issue here (https://facebook.github.io/flux/) other than that I like it. Also we have to check domain availability before we pick any name.

**Comment by alissapajer** [comment]
Thinking along the lines of what "scodec" did, we could also add an "s" (s for Scala) to the beginning (or end) or any word. "sflux" or "sflow" for example.

I also like "streamz" quite a bit. When speaking, I already say "streams" to mean "scalaz-stream".

**Comment by pchiusano** [comment]
Good point about flux. With flux, we could disambiguate by saying Scala Flux, so I don't think that should be a dealbreaker if we really like that. Pretty much every name of that sort is going to be taken by some piece of software.

**Comment by pchiusano** [comment]
Here's a [logo / homepage variation for 'streamz'](https://docs.google.com/drawings/d/1-3SKaccBjIenCPNWSD_f8nrHpBvPqyvD6OoUYtqiPg8/edit?usp=sharing) I just did.

**Comment by milessabin** [comment]
What about "fluxus"?

**Comment by aloiscochard** [comment]
+1 for `streamz` as it's how people already often refer to it on IRC/online.

**Comment by andreaferretti** [comment]
+1 for aqueduct

**Comment by alissapajer** [comment]
I like "fluxus" too. 

"ducts" alone might not be good because everyone hears "ducks" so we could just go with "ducks" and then there would be "ducks" and "cats"

**Comment by runarorama** [comment]
Just want to throw my hat in and suggest Ryū, or 流.

https://en.wiktionary.org/wiki/%E6%B5%81

**Comment by runarorama** [comment]
ryu.io, flow.io, are available. Most second-level domains names "streamz"
are taken.

**Comment by pchlupacek** [comment]
sflux is perhaps used too http://sflux.sourceforge.net/. 
 @runarorama  sure that ryu does not have `different` context meaning in cantonese? If not I like it. it is short and perhaps we can simplify the cantonese letter for the logo.

**Comment by levinotik** [comment]
Not saying it matters, but it seems someone else had the same idea :) https://github.com/softprops/ryu

**Comment by adelbertc** [comment]
There's already a "streamz" that actually uses scalaz-stream :-) https://github.com/krasserm/streamz

**Comment by pchiusano** [comment]
That is good to know.

**Comment by runarorama** [comment]
Along those lines, Phi or Psi, which are often used as symbols for magnetic
and electric flux, respectively.

I quite like the sound of "Fluent". It's a shame that fluent.io seems to be
taken.

**Comment by pchiusano** [comment]
Thought of a couple other ideas, basically use 'z' in place of 's':

zflux, zflow, zflo, z-flo, zflux.io, zflow.io, zflo.io

I really dislike "fluxus" for some reason.

**Comment by InTheNow** [comment]
Using the "Sc" from Scala.... "Screams".

**Comment by djspiewak** [comment]
I'm a fan of Flux (and not a fan of fluxus).  Fluent sounds pretty amazing as well.  Streamz matches the common vernacular, but it directly conflicts with a first-order downstream project.

One thing you could do with flux is get creative with the phonetics: flucz, or flukz (though I think most native english speakers would pronounce the latter like "flukes").

**Comment by InTheNow** [comment]
As a stream is more like a longitudinal wave - how about "Slinky". Sounds cool, too

**Comment by adelbertc** [comment]
Came up on my Twitter stream, apparently there's a [rx-flux](https://github.com/fdecampredon/rx-flux) project that's stream-ish, though it appears to be specifically for JavaScript.

**Comment by gruggiero** [comment]
Given that Scala is an italian word, what about Flusso?

**Comment by huntc** [comment]
ssssstream

**Comment by runarorama** [comment]
I quite like flusso. Sounds friendly.



—

**Comment by ShengC** [comment]
My feeling is no matter what name is chosen, it won't be as good as
scalaz-stream whatsoever. Considering the library that serves the similar
purpose, rx java, Akka-stream. They are not fancy names, but hardly
forgettable.

**Comment by mmynsted** [comment]
currents?

**Comment by fiadliel** [comment]
I've been using this library in work, and more than once I've had to explain how what I was doing was different to “using scalaz”. And, sadly, that is often considered a difficult and negative thing. So while I have positive feelings for scalaz, I would prefer nothing with a 'z' in the name.

Both "flux" and "streams" sound good to me, especially the second. Simple, and perhaps a touch arrogant, but hey, this _is_ the preeminent Scala streaming library.

**Comment by runarorama** [comment]
+1 to currents



—

**Comment by adelbertc** [comment]
:+1: flusso, currents

**Comment by SethTisue** [comment]
Flux is taken. I like Currents and Aqueduct.

**Comment by etorreborre** [comment]
I've been using `streamz` and I like it. Keeping the `z` on the other hand might give the idea that it is still related to `scalaz`. 

So I would probably go with `streams` or `scala-streams` as I don't see a reason to drastically change the name. (but hey who am I to give naming advices after `specs2` :-)).

**Comment by omidb** [comment]
`Amps` or `Ampere` the SI unit for electricity current

**Comment by markkrueger** [comment]
Interstate
Autobahn
Tributaries
Traffic Cop
Tapestry
Weave

**Comment by mpilquist** [comment]
+1 for ryu and currents

**Comment by orionll** [comment]
How about `machinez`? `streamz` is also good

**Comment by som-snytt** [comment]
What a challenging problem. I hope you manage to avoid anything that evokes bodily functions.

Isn't fluxus what afflicts travellers? Flusso might be an Italian brand of toilet, and not of the highest line. Marketed overseas as EZ-flo.

Bächle unfortunately suggests debacle, in the American pronunciation.

流 has the advantage, like scalaz, of starting interminable threads about how to pronounce it, with the various camps digging in, convinced they are right because in fact they are.

I would definitely get the tattoo done, and a clever ink artist might be able to reuse the z from my scalaz tattoo, which has begun to sag anyway.

The Freiburg link uses runnels and rills. Rills offers combinations: Thrills, frills, krill. Frills spelt with a phi, φrills. Would people mistake it for theta and pronounce it thrills after all?

Runnel might be too close to Runar. Runnelorama.

Or +1 currents. +2 currants or any fruit really.

**Comment by fthomas** [comment]
Runnelorama is definitely the best suggestion so far! :+1: Awesome @som-snytt

**Comment by fthomas** [comment]
Btw, suggestions based on `Process`, the main data type of the library, would be interesting too.

**Comment by japgolly** [comment]
Many have mentioned that Flux is taken (in the JS space). What's probably not as well known is that I often get asked about whether scalajs-react will absorb it. It will not, but community desire seems to be there. I doubt it will be long before someone creates a ScalaJS port of Flux - maybe scalajs-flux, maybe Scala Flux.

Ryuu makes me think of Street Fighter (although it's probably 竜).

+1 for `streamz` and `Aqueduct`.

Here's an idea: how about ⚶ and we start calling it "The Library Formerly Known as Scalaz-Stream".

**Comment by milessabin** [comment]
+1 for currents, but no way is that domain going to be available :-(

**Comment by InTheNow** [comment]
+1 `scala-streams` - "The Scala Streams Library"

-10 for my daft ideas  ^^

**Comment by rslima** [comment]
How about fluxez? Too weird?

**Comment by som-snytt** [comment]
Suez = Streams und ends in z.

**Comment by runarorama** [comment]
Tuebz was the original name of Machines :)

Paul didn't like it.



—

**Comment by pchiusano** [comment]
Okay, after deep meditation on this issue :), I am ruling out flux, flow, currents, and all the names in that vein. I was briefly excited about naming it after a river, especially since there are a lot of cool river names. But I decided I'd like to just do something really simple, along these lines:

* Functional Streams for Scala (FSS or FS2)
* Functional Scala Streams (FSS or FS2)
* Scala Functional Streams (SFS)
* Scala Functional Streams Library (SFSL)
* Scala Streams Library (S2L)
* Scala Streams (S2) (incidentally, scalaz-stream has the same two letter code)
* Functional Streams Library (FSL)

In conversation you could refer to the library as just Streams, Scala Streams, etc, or via 'FS2' or whatever the letter code is.

Thanks to people who have piped in with ideas. From this point forward, I'd just like to hear from contributors to the library - anyone who has contributed a line of code or at least a bug report. Everyone else, please pipe in only if there's something horribly wrong with any of the names or. (Like knowing that streamz was taken was helpful.)

For contributors, let me know which of these you like best and any that you hate (or which are taken). If you think of any variations along these lines feel free to offer those up as well.

As far as domain names go, there is some variation on the domain name that is available for all these, especially if you use some of the newer domain name extensions like `.tech`, etc.

**Comment by mmynsted** [comment]
If you can't get currents domain, then how about currentz?

**Comment by rslima** [comment]
Well, I  believe that Scala Streams would be the easier transition. Now I
was wondering why are you dropping the dependency on scalaz?

On Sun, Aug 16, 2015 at 10:33 PM, mmynsted <notifications@github.com> wrote:

> If you can't get currents domain, then how about currentz?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scalaz/scalaz-stream/issues/428#issuecomment-131649191>
> .
>



-- 
Ricardo da Silva Lima
rslima@gmail.com

**Comment by pchlupacek** [comment]
Just few remarks. 

Java8 is getting its stream package. For beginners even samples presented may seem familiar. Are we ok that there may be sort of confusion between ppl about which stream library they talking? 

Not sure if we shal have two 's' letters in abbreviation. its hard to prnounce and may still have conflicting meaning in some regions.

Not sure that we have to include 'Scala' in the name. are we abosutely sure there won't be any ports or api's (i.e. java 8) where scala may just not be good thing in part of the name? 

I like the last one best Functional streams library or Fsl. honestly i like abbreviation better than the name. I don't like the 'Library' in the name. Cannot however get better proposition. I d like to express somehow better that we are strong in 'orchestration' of complex processes including the effects as the functional shall already express reuse and purity.

**Comment by pchlupacek** [comment]
just perhaps small idea. How about Functional Stream Tooling? or FST?

**Comment by dwijnand** [comment]
> I am ruling out flux, flow, currents, and all the names in that vein.

@pchiusano I'm curious as to why.

I'm personally biased towards untaken, short, single-barrel names, to avoid any form of confusion, for instance hyphenated vs dot-delimited, belonging to the scala library, or the scala modules (ala xml), etc..

My vote (fwiw) is therefore for Ryu, seeing as https://github.com/softprops/ryu is a 2010 Scala 2.7.7 project. It's short, it's single-barrel.. and it comes with its own, free logo (流).

**Comment by pchiusano** [comment]
Functional Streams Toolkit would work, along those lines. 

We could also work effectful into the name, but I don't know if that word means much to people. 

Effectful Functional Streams (EFS)
Effectful Streams for Scala (ES2)

Other contributors do you want to weigh in?

**Comment by runarorama** [comment]
Functional Streams Library (FuSLi).

**Comment by pchlupacek** [comment]
:-) @runarorama I got simillar idea: FiST ( FunctIonal Streams Toolkit) but it sounded too aggressive :-)

**Comment by milessabin** [comment]
@runarorama googling for fusli gets me "Showing results for fusilli" ... However, fusilli is pretty good and fusilli.io is available.

**Comment by gruggiero** [comment]
I'm not a contributor, but maybe this is good to know:

fusilli is an italian pasta that resembles spaghetti, maybe is not the best
name to give to a software library :)

**Comment by milessabin** [comment]
It doesn't resemble spaghetti at all, it's a rather elegant spiral, designed for optimal flow of sauce.

**Comment by gruggiero** [comment]
There are more fusilli in heaven and earth, Miles,
than are uses of _ in scala

Sorry, I couldn't resist :)
I'll silently retreat...

**Comment by pchiusano** [comment]
Maybe FUSL for functional streams library, but we could always just refer
to it as FUSL or Fusl.

**Comment by pchlupacek** [comment]
How about instead of library use `machines`? This is to me better expressing the orchestration nature of the library itself. 

- Functional Stream Machines (FSM)  // this unfortunately messes with FSM, which I am not sure if it is good or bad but http://www.fsm.io/ seems to be available

**Comment by aloiscochard** [comment]
Just wanted to say that refering to the lib as `streams` would be very confusing, due to `akka-streams`.

+1 for fusilli
-1 for acronyms

**Comment by cvogt** [comment]
"Hej I started using Scala Streams!" - "Which one? The ones in the standard library or the Typesafe ones?" - "No the other ones, that used to be called Scalaz Stream." - "Does it need Scalaz?" ...

A too generic name may indeed cause confusion.

Here's another one: **DaFlow** (Directed Asynchronous Flow / Data Flow). Goes well in language as well. "Hej you got DaFlow?" - "Yeah, I got DaFlow" - "DaFlow FTW"

Or variations of that. **Aflo**, **Aflow**.

Or **Wolf**... Flow reversed. **Reactive Wolf**? **Radioactive Wolf**? Ok, I am out.

**Comment by pchiusano** [comment]
Contributors, let me know if you have any final thoughts in the next 24
hours. I'll decide after that.

**Comment by som-snytt** [comment]
Please excuse the spam slash Swiss culture plug: Fuseli works in the effectful e. Also Fuessli.

**Comment by runarorama** [comment]
We can call ourselves Füssli Bünzlis.

**Comment by pchlupacek** [comment]
I love to see @milessabin logo of perfect fussilli with perfection of the sauce flowing in spiral screw of it :-)

**Comment by runarorama** [comment]
The Scala logo kind of looks like fusilli.



—

**Comment by refried** [comment]
flux also means changing (eg no stable api) so I’m glad it’s been ruled out.  

fstream? f for functional

or keep the current name even once there's no dependence on scalaz

**Comment by pchiusano** [comment]
Tentative decision: 

FS2: Functional Streams for Scala

Package name will be `fs2`, library can be referred to as FS2 in conversation. The `fs2.tech` domain is available. Probably some others.

Honestly, this is not super urgent, so if anyone comes up with a brilliant idea before the release, we can always consider it. Until then I'm going to keep calling it scalaz-stream, otherwise it's going to be super confusing.

**Comment by ShengC** [comment]
How about stream4s ?

**Comment by pchiusano** [comment]
I actually quite like that! Great...

**Comment by som-snytt** [comment]
You can use this, and say, "It's not an ess, it's our coat of arms. It means streamz, or stream4s; it kind of looks like a fusilli."

[super-streamz](https://en.wikipedia.org/wiki/File:Superman_shield.svg)

**Comment by ahjohannessen** [comment]
I think `stream4s` is quite nice :+1: I think the `http4s` guys agree :)

**Comment by pchiusano** [comment]
Okay, now that I am wrapping up work on the redesign branch, I'm finalizing a name. I've decided to go with FS2: Functional Streams for Scala, my original pick. I do like stream4s (and S4S) but find them a little tough to pronounce with the two 's'. 'FS2' rolls off the tongue more... 

In terms of referring to the library, I am going to use the name FS2, capitalized just like that. Or longer form 'FS2: Functional Streams for Scala'. The package name is `fs2`, lowercase.

Thanks to everyone who participated in this discussion. I'll explain my thinking a little bit more. Obviously, this is all very subjective:

* There were a lot of cool names, like Ryu and so on. I liked some of these. But I thought a more generic name was better. The old name, scalaz-stream, is very generic. It just felt too weird to me to switch the project to a name with a non-generic name. It felt too much like the library was totally changing identities.
* FS2 just sounded the nicest to me of the generic names (I really liked 'streamz', but that was taken). I liked some of the others too (like FST: Functional Streams Toolkit) but just preferred FS2 for some reason.

To fully put this to bed, I renamed the package in the redesign branch and went ahead and reserved http://fs2.co. The `fs2.tech` one was considerably more expensive, but it's also available if someone wants to reserve that too. Presently, fs2.co redirects here, but we can redirect somewhere more useful later, probably a github pages based site which hosts documentation, API docs, a fancy landing page with a cool logo, a [design by humans web store](http://www.designbyhumans.com/) with cool project t-shirts, you name it. The fancy landing page is really the most important part, since that's how most programmers decide on what libraries to use. :)

I wanted to create a new GitHub organization which will serve as the new umbrella org for this project and maybe other related projects, but [fs2](http://github.com/fs2) is taken (by an organization with no public members or repos - maybe a closed-source shop?), so I went with `functional-streams-for-scala`. Kinda wordy. I think we should hold off on migrating anything there until after the #430 release.

**Comment by pchiusano** [comment]
Just to clarify, the new naming will take effect with the first release incorporating the new library design. There will likely be a more conservative 0.8 release with the current design, based off current master, and I think that should still be named scalaz-stream to keep moving parts on that release to a minimum.

**Comment by etorreborre** [comment]
It's probably to late to comment but I wonder if the `2` in `fs2` conveys "version 2", a bit like "Java 2" and, hmm, "specs2". Why did you prefer `fs2` over `fss`?

**Comment by pchiusano** [comment]
That is not a terrible association, honestly. It is a substantial redesign
of the library from its initial version. Also FS2 is easier to pronounce. :)

**Comment by ms-tg** [comment]
I can contribute that a Scala Times link brought be to the FS2 design document, and I understood it to mean "Functional Streams 2". I assumed this meant that (1) scalaz dependency was being removed, and replaced by the generic concept "functional", and (2) this was a substantial evolution of scalaz-stream, hence the "2".

It appears that, even though the "2" really refers to the two 's' characters in acronym of Streams for Scala, my ignorant alternate interpretation was largely correct regardless. Therefore, I'd argue it's a good choice of name.

**Comment by ms-tg** [comment]
(sorry, just to add: I came to this ticket by googling "pchiusano fs2", in an effort to find out more about FS2)
