### ISSUE TITLE
Resource safety testing of new design

### ISSUE THREAD

**Issue by pchiusano** [scalaz/scalaz-stream#442]
Goal: a solid test suite that gives us confidence that resource safety is being handled correctly with the new design. 

More specifically, come up with list of scenarios to test resource safety of the new design, especially in conjunction with asynchronous operations. Part of this is brainstorming, and part of it is actually implementing the tests. I'd like to take the lead on this, but we should all try to come up with ideas for tricky scenarios that need testing. If you have ideas please post them here!

I'll reference the existing resource safety tests (some of which will still be relevant), and I'll also try to come up with others. I might start with just some informal descriptions of different scenarios before diving into writing the test suite. Once the test suite is implemented, it might give people ideas for possible variations.

After I've implemented the test suite, I'll link to it from here and this might spur some further ideas of things to test.

Review by @djspiewak @pchlupacek @alissapajer @radekm

**Comment by pchiusano** [comment]
Okay, I thought of a list of scenarios to test that `bracket` behaves as expected wrt resource safety. I'm going to start implementing these, but if others have ideas please pipe in!

* exception inside an effect, as in `eval(Task.delay(throw Fail))`
* exception in pure code - `blah.map(x => throw Fail)`
* normal termination of bracket, no exceptions
* `bracket(..) ++ bracket(..) ++ ... ` 1 million times, checking for interpreter memory leak. Repeat same test with unchunked code, which has to pass through the `Pull` interpreter as well.
* early termination - `bracket(..).take(3)`
* multiple levels of early termination - `bracket(..).take(m).take(n)`, for various choices of `n`, `m`

### Asynchronous resource allocation

* Scenarios like `fail(err) merge bracket(..)` should always run the bracket's cleanup action, even though the resource is being acquired asynchronously
* Multiple levels of asynchronous resource allocation - `bracket(..).prefetch(m).prefetch(n)`
* Test of `concurrent.join`, which exercises a lot of stuff if the inner streams are `bracket`-based streams

**Comment by pchiusano** [comment]
I've made some good progress on these, and Scalacheck already spotted some bugs that I've fixed. I'm still working on the async resource allocation tests. I have one, currently commented out because it's failing! I'm working on fixing that now.

https://github.com/scalaz/scalaz-stream/blob/topic/redesign/src/test/scala/fs2/ResourceSafetySpec.scala

Again, if anyone has ideas for evil scenarios to test let me know!

**Comment by pchlupacek** [comment]
perhaps in nested bracket scenario, if finalizer fails, do the upper finalizers get executed?

**Comment by pchiusano** [comment]
Good idea.

**Comment by pchiusano** [comment]
Closing this, but that doesn't mean we can't add more tests as we think of them.
