### ISSUE TITLE
Replace Either by Try in fs2.util.Task

### ISSUE THREAD

**Issue by pchlupacek** [scalaz/scalaz-stream#456]
Just an idea. I believe `scala.Try` type has better suit for failure representation then scala's Either, probably as well resulting in better readable code.

**Comment by pchiusano** [comment]
`Try` does some weird stuff, like not catch all exceptions: https://github.com/scala/scala/blob/2.11.x/src/library/scala/util/Try.scala#L230 I don't really like it. However, if people would like to convert the result of `attemptRun` to a `Try` in their own code, they are free to go for it.

Even though it might clean up some of the internal code, I don't really want to introduce a new type just to get a right-biased `Either`. `Either` is good enough for us internally, and people can convert it to something else if they really want.

**Comment by pchlupacek** [comment]
@pchiusano fair enough. Was just idea to share before it won't be possible before amount of the work. I hate Either, and Try isn't that much better, however will give us straight conversion to lot of `scala` written code. 

Lets then close it.
